### ISSUE TITLE
[question] how to use array data in VegaLite

### ISSUE THREAD

**Issue by HaveF** [vega/react-vega#249]
Thanks for this repo.

About the `import { VegaLite } from 'react-vega'`, [it says](https://github.com/vega/react-vega/tree/master/packages/react-vega#approach3-use-vegalite-generic-class-and-pass-in-spec-for-dynamic-component), `data` attribute is a plain object instead of an array.
```js{1}
const spec = {
  width: 400,
  height: 200,
  mark: 'bar',
  encoding: {
    x: { field: 'a', type: 'ordinal' },
    y: { field: 'b', type: 'quantitative' },
  },
  data: { name: 'table' }, // note: vega-lite data attribute is a plain object instead of an array
}
```

But how can I deal with array data?

`[{ "name": "table1"... }, { "name": "table2"... }]`

I searched a lot, but without luck.
Thanks in advanced!

**Comment by paulrosenzweig** [comment]
This issue is three years old, but I hit the same thing. I'll post what I found here for future searchers.

When you use the `data` prop on the Vega or VegaLite components, react-vega sets the data at runtime using the view API's [data method](https://vega.github.io/vega/docs/api/view/#view_data). Doing that in Vega-lite requires an empty [named data source](https://vega.github.io/vega-lite/docs/data.html#named).

Something like this will work:
```js
<Vega
  data={{myData: [{value: 1}, {value: 2}]}}
  spec={{
    data: {name: "myData"},
    ...rest of spec
  }}
/>
```

Alternatively, you can include the data in the spec itself:

```js
<Vega
  spec={{
    data: {values: [{value: 1}, {value: 2}]},
    ...rest of spec
  }}
/>
```

**Comment by HaveF** [comment]
@paulrosenzweig thanks for your answer.
Maybe my question is not clear enough.
I mean, if I have two or three data sources and want to use vega lite's concat or some other way to combine them, what can I do?

For now I still have no answer. 
But I combine all data together and use filter to split them. It is not elegant, but it works.

**Comment by paulrosenzweig** [comment]
@HaveF ah sorry I misunderstood. I think your issue is really with Vega-lite rather than react-vega. Vega-lite specs have one primary data source and you want to use multiple. Is that your issue?

You'll want to include the multiple datasets as part of the spec rather than using react-vega's data property. [Here's an example](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQcWVDYATGrLJpQAD10gAZjTiD1aEAaWYAnjjiWAjgySzMdJB9IgAvkttDEzMLdECbe0d0FzcPTC8aH19-EEEkWzgAJzQAbVB1LxRUUGIkQQY4CFz9NAAGALQARn8a1EaG1FrfAF0U5EyAa0thWUcWkAL4w1LyyuqrOo6uhVb2kEC2nr6kQeGtMd6gA) using layer. That didn't work with concat, so I think there are some limitations/bugs.

**Comment by HaveF** [comment]
@paulrosenzweig Nice. Hidden secret. Thanks for your share! ❤️
