### ISSUE TITLE
Lighter dependencies

### ISSUE THREAD

**Issue by domoritz** [vega/react-vega#36]
It would be great to reduce the dev-dependencies to only the essential so that we don't end up in a situation where some library is not supported anymore soon. Maybe once we switch to typescript (#25), we can use that instead of Babel.

**Comment by kristw** [comment]
I am using shared `build-config` across multiple projects (several projects from Airbnb use this) so I only have to maintain single build process instead of setting up each project differently. 

It has support for `babel`, `eslint`, `jest`, `typescript` and has multiple people helping take care of it.

**Comment by domoritz** [comment]
Sweet. Are you volunteering to maintain the dev dependencies? :-D

**Comment by kristw** [comment]
I have to do it for the other projects anyway, so yes.

**Comment by domoritz** [comment]
Thank you.
